version: "3.8"

services:
  app:
    image: ndrek/fearlessdraft-app:${IMAGE_TAG}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
      restart_policy:
        condition: any
    ports:
      - "3000:80"
    networks:
      - app-network

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: overlay

configs:
  nginx_config:
    file: ./deployment/fearlessdraft-app/nginx.conf